version: 2
jobs:
  build:
    working_directory: ~/tinykitten
    docker:
      - image: circleci/node:8.12
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: lint
          command: yarn lint
      - run:
          name: Generate static files
          command: yarn generate
